services:
  redis:
    image: "redis/redis-stack:latest"

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.db-env
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - env/.project-env
      - env/.db-env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: