# Generated by Django 5.1.3 on 2024-11-14 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата получения xml с данными о продуктах', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Xml-файл',
                'verbose_name_plural': 'Xml-файлы',
                'indexes': [models.Index(fields=['date'], name='parser_xml_date_8da3ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Количество товаров не может быть отрицательным')], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('category', models.CharField(choices=[], max_length=255, verbose_name='Категория')),
                ('xml_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser.xml', verbose_name='Xml-файл')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Ответ LLM', verbose_name='Текст анализа продаж')),
                ('xml_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='parser.xml', verbose_name='Xml-файл')),
            ],
            options={
                'verbose_name': 'Анализ продаж',
                'verbose_name_plural': 'Анализ продаж',
            },
        ),
    ]
