# Generated by Django 5.1.3 on 2024-11-18 12:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL-адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник для получения xml-файла',
                'verbose_name_plural': 'Источники для получения xml-файлов',
            },
        ),
        migrations.CreateModel(
            name='Xml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата получения xml с данными о продуктах', verbose_name='Дата')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_files', to='parser.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Xml-файл',
                'verbose_name_plural': 'Xml-файлы',
            },
        ),
        migrations.CreateModel(
            name='SalesAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Промпт для LLM', verbose_name='Текст запроса на анализ продаж')),
                ('text', models.TextField(help_text='Ответ LLM', verbose_name='Текст анализа продаж')),
                ('xml_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='parser.xml', verbose_name='Связанный xml-файл')),
            ],
            options={
                'verbose_name': 'Результат анализ продаж',
                'verbose_name_plural': 'Результаты анализов продаж',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Количество товаров не может быть отрицательным')], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('category', models.CharField(choices=[('Electronics', 'Электроника'), ('Food', 'Продукты'), ('Clothes', 'Одежда'), ('Furniture', 'Мебель')], max_length=255, verbose_name='Категория')),
                ('xml_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser.xml', verbose_name='Xml-файл')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddIndex(
            model_name='xml',
            index=models.Index(fields=['date'], name='parser_xml_date_8da3ce_idx'),
        ),
    ]
